AWSTemplateFormatVersion: 2010-09-09
Transform: "AWS::Serverless-2016-10-31"
Description: P3

Resources:
  A3L1:
    Type: "AWS::Serverless::Function"
    Properties:
      FunctionName: IndexPhotosLF1
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri: ./LF1
      Description: LF1
      MemorySize: 128
      Timeout: 30
      Role: "arn:aws:iam::824208337648:role/service-role/index-photos-role-wa3amddo"
      Layers:
      - arn:aws:lambda:us-east-1:770693421928:layer:Klayers-p38-requests:7
      - arn:aws:lambda:us-east-1:770693421928:layer:Klayers-p38-opensearch-py:6
      Environment:
        Variables:
          REGION: us-east-1
  A3L2:
    Type: "AWS::Serverless::Function"
    Properties:
      FunctionName: SearchPhotosLF2
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri: ./LF2
      Description: LF2
      MemorySize: 128
      Timeout: 30
      Role: "arn:aws:iam::824208337648:role/LambdaExecutionRoleLF1"
      Layers:
      - arn:aws:lambda:us-east-1:770693421928:layer:Klayers-p38-requests:7
      - arn:aws:lambda:us-east-1:770693421928:layer:Klayers-p38-opensearch-py:6
      Environment:
        Variables:
          REGION: us-east-1
